language: go
arch:
    - amd64
    - ppc64le

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip
matrix: 
   allow_failures:
    - go: 1.9.x
    - go: 1.10.x
    - go: tip


script:
  - go vet ./...
  - go test -timeout 1h ./...
  - go test -timeout 30m -race -run "TestDB_(Concurrent|GoleveldbIssue74)" ./leveldb
